# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

2. Create a null vector of size 10 

In [8]:
x=np.zeros((10))
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [10]:
x=np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [11]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [12]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration

In [18]:
np.__version__
np.__config__

<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>

7. Print the dimension of the array in question 3


In [20]:
x.ndim

1

8. Create a boolean array with all the True values

In [21]:
x=np.ones(10, dtype='bool')
x

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [22]:
x=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
x.ndim

2

10. Create a three dimensional array



In [25]:
x=np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[2,3,4,5,6]]])
x.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [29]:
v = np.arange(1, 10)
x=v
print("actual array : ",x)
y=v[::-1]
print("reverse order : ", y)

actual array :  [1 2 3 4 5 6 7 8 9]
reverse order :  [9 8 7 6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [30]:
x= (np.arange(10) == 4).astype(int)
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [31]:
x= np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [32]:
x= np.array([1, 2, 3, 4, 5])
x= x.astype(float)
print(x.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [34]:
x= np.array([[1., 2., 3.], [4., 5., 6.]])
y= np.array([[0., 4., 1.], [7., 2., 12.]])
print(x.dot(y.T))

[[ 11.  47.]
 [ 26. 110.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [35]:
np.maximum(arr1, arr2)

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [37]:
x = np.arange(0, 10)
y = x[x % 2 != 0]
print(y)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [ ]:
x[x % 2 == 1] = -1
print(x)

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [38]:
x = np.arange(10)
x[5:9] = 12
x

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [39]:
x = np.ones((5, 5))
print("Actual array: ")
print(x)
print("Printing 0's inside array: ")
x[1:-1, 1:-1] = 0
print(x)

Actual array: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Printing 0's inside array: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [40]:
x= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print([[i if i!=5 else 12 for i in j] for j in x])

[[1, 2, 3], [4, 12, 6], [7, 8, 9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [41]:
x= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Actual array", x)
x[0:1, 0]= 64
print("Modified array: \n", x)

Actual array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Modified array: 
 [[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [42]:
x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print("Actual array", x)
print("Sliced array: \n", x[0:1, :])

Actual array [[0 1 2 3 4]
 [5 6 7 8 9]]
Sliced array: 
 [[0 1 2 3 4]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [43]:
x= np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print("Original array", x)
print("Sliced 2nd value from 2nd 1-D array:",[1, 1])

Original array [[0 1 2 3 4]
 [5 6 7 8 9]]
Sliced 2nd value from 2nd 1-D array: [1, 1]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [50]:
x = np.arange(10).reshape(2,5)
print("Original array:", x)
print("Sliced array:", x[0:2, 2:3])

Original array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Sliced array: [[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [45]:
arr_10x10 = np.random.randn(10, 10)
print("Max value: ", np.max(arr_10x10))
print("Min value: ", np.min(arr_10x10))

Max value:  3.3830944554861184
Min value:  -2.7040497051218577


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Common items in a and b are: ", np.intersect1d(a, b))

Common items in a and b are:  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [48]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Positions where items of a and b matches are: ", list(np.flatnonzero(np.in1d(a, b))))

Positions where items of a and b matches are:  [1, 3, 5, 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [51]:
mask = (names != "Will") & (names != "Joe")
data[mask]

array([[-0.36778113, -1.17253358,  0.60404019, -0.1177478 ],
       [ 0.80999411, -1.71533747,  1.22950024,  0.71578006]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [52]:
x = np.random.randint(low=1, high=15, size=(5,3)) + np.random.randn(5,3)
x

array([[14.94528981,  1.99605661,  8.47853132],
       [10.54576978,  1.32297295,  7.13506765],
       [11.67719284,  5.17304995,  1.49296561],
       [13.81412495,  2.81436995,  8.81909528],
       [10.42116944,  1.15281452,  2.31950378]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [54]:
x = np.random.uniform(low=1, high=16, size=(2,2,4))
x

array([[[14.58143202,  2.70803823,  3.06727019, 11.93068404],
        [13.09976401, 11.86375652, 13.17009136,  7.40444688]],

       [[ 6.3754594 ,  5.05512952,  2.29701303, 15.19704878],
        [ 1.31478122,  9.85123038,  8.72713589, 11.43687389]]])

33. Swap axes of the array you created in Question 32

In [55]:
Q_32_array.reshape(4,2,2)

array([[[ 6.26604087,  6.93237233],
        [ 3.93980625,  3.1646361 ]],

       [[11.70378815, 14.90473124],
        [ 1.54737241,  9.06160284]],

       [[10.44488431,  1.69719369],
        [15.21796949,  4.0943089 ]],

       [[ 8.70505476, 15.08702392],
        [ 5.25419331, 14.46676696]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [58]:
x = np.arange(0, 2, 0.2)
print("Original array: ", x)
x = np.array([np.sqrt(i) for i in x])
x[x < 0.5] = 0
print("Array after replacing values less than 0.5: \n", x)

Original array:  [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
Array after replacing values less than 0.5: 
 [0.         0.         0.63245553 0.77459667 0.89442719 1.
 1.09544512 1.18321596 1.26491106 1.34164079]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [59]:
a = np.random.randn(12)
b = np.random.randn(12)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [60]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [61]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [62]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[0:, 1] = newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [63]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [64]:
import random
random_matrix = np.array([[random.random() for i in range(5)] for j in range(4)])

In [65]:
random_matrix

array([[0.31168111, 0.19496047, 0.56289937, 0.28488969, 0.98168535],
       [0.09825231, 0.00098487, 0.32746233, 0.45482063, 0.6844125 ],
       [0.30666819, 0.73815938, 0.32824329, 0.05537406, 0.97743421],
       [0.9096009 , 0.55989335, 0.89860834, 0.82311794, 0.44453981]])

In [66]:
np.cumsum(random_matrix, axis=0)

array([[0.31168111, 0.19496047, 0.56289937, 0.28488969, 0.98168535],
       [0.40993342, 0.19594535, 0.8903617 , 0.73971032, 1.66609785],
       [0.7166016 , 0.93410473, 1.218605  , 0.79508438, 2.64353206],
       [1.6262025 , 1.49399808, 2.11721334, 1.61820232, 3.08807188]])